/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ManagementSystem.Encounter;
import ManagementSystem.EncounterDirectory;
import ManagementSystem.House;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apurv
 */
public class CommunityData extends javax.swing.JPanel {

    /**
     * Creates new form CommunityData
     */
    Stack<Encounter> s;
    ArrayList<House> ah;
    HashSet<String> sAge = new HashSet<>();
    HashSet<String> sHouse = new HashSet<>();
    DefaultTableModel dtm;
    int count = 0;
    public CommunityData(Stack<Encounter> s, ArrayList<House> ah) {
        initComponents();
        this.s = s;
        this.ah = ah;
        for(House h:ah)
            sHouse.add(h.getCommunity());
        for(String scm: sHouse)
            cmbxCommunity.addItem(scm);
        for(Encounter e:s)
            sAge.add(e.Group);
        for(String aGrp:sAge)
            cmbxAgeGrp.addItem(aGrp);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbxCommunity = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblCnt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbxAgeGrp = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abnormal Data");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 795, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select Community:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 65, -1, -1));

        cmbxCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxCommunityActionPerformed(evt);
            }
        });
        add(cmbxCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 64, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Count of People with Abnormalities:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 395, -1, -1));

        lblCnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblCnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 395, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Age Group:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 65, -1, -1));

        add(cmbxAgeGrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 64, -1, -1));

        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("Get Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 263, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "City", "Community", "ID", "Blood Pressure"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 117, 739, 95));

        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 263, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Collections.reverse(s);
        dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        for(Encounter et:s){
            Object [] row= new Object[7];
            String ageGrp = cmbxAgeGrp.getSelectedItem().toString();
            String cm = cmbxCommunity.getSelectedItem().toString();
            boolean a1 = et.getGroup().equalsIgnoreCase(ageGrp);
            boolean a2 = et.getCommnuity().equalsIgnoreCase(cm);
            boolean a3 = et.isIsAbnormal();
            if(et.isIsAbnormal() && et.getGroup().equalsIgnoreCase(ageGrp) && et.getCommnuity().equalsIgnoreCase(cm)){
            row[0]= et.getName();
            row[1]=et.getAge();
            row[2]=et.getGender();
            row[3]=et.getCity();
            row[4]=et.getCommnuity();
            row[5]=et.getPersonID();
            row[6]=et.getBloodPressure();
            dtm.addRow(row);
            count++;
            }
	}
        lblCnt.setText(String.valueOf(count));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        count = 0;
        lblCnt.setText(String.valueOf(count));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbxCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbxAgeGrp;
    private javax.swing.JComboBox<String> cmbxCommunity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCnt;
    // End of variables declaration//GEN-END:variables
}
