/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Car;
import model.CarHist;

/**
 *
 * @author aishw
 */
public class CreatePanel extends javax.swing.JPanel {
    CarHist hist;
    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(CarHist hist) {
        initComponents();
        this .hist = hist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        lblCarMake = new javax.swing.JLabel();
        lblNoOf_Seats = new javax.swing.JLabel();
        lblModel_year = new javax.swing.JLabel();
        lblModel_No = new javax.swing.JLabel();
        lblExpiry_Maintenance = new javax.swing.JLabel();
        lbl_Serial_NO = new javax.swing.JLabel();
        txtCar_Make = new javax.swing.JTextField();
        txt_serial_No = new javax.swing.JTextField();
        txt_Model_No = new javax.swing.JTextField();
        txt_Date = new com.toedter.calendar.JDateChooser();
        jButton_save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtYear = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSeats = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtExpiry = new javax.swing.JTextField();
        lblModel_Year = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblSerial_No = new javax.swing.JLabel();
        lblModelN = new javax.swing.JLabel();
        lblAv = new javax.swing.JLabel();
        lblCITY = new javax.swing.JLabel();
        lblExpiry_Status = new javax.swing.JLabel();
        lblError_Make = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Car");

        lblCarMake.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCarMake.setText("Car Make");

        lblNoOf_Seats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoOf_Seats.setText("No. of Seats ");

        lblModel_year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblModel_year.setText("Model Year ");

        lblModel_No.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblModel_No.setText("Model No.");

        lblExpiry_Maintenance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExpiry_Maintenance.setText("Expiry Maintenance");

        lbl_Serial_NO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Serial_NO.setText("Serial No.");

        txtCar_Make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCar_MakeActionPerformed(evt);
            }
        });

        txt_serial_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serial_NoActionPerformed(evt);
            }
        });

        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtYear);

        jScrollPane3.setViewportView(txtSeats);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Availability");
        jLabel1.setRequestFocusEnabled(false);

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });

        lblCity.setText("City :");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        jLabel2.setText("Expiry");

        lblModel_Year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblModel_YearKeyTyped(evt);
            }
        });

        lblError_Make.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblError_Make.setForeground(new java.awt.Color(255, 0, 0));
        lblError_Make.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblError_MakeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel_year, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoOf_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Serial_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel_No, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpiry_Maintenance)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCity)
                        .addComponent(txt_Model_No, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(txt_serial_No, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(txtCar_Make, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAvailability, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jButton_save)))
                    .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel_Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerial_No, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelN, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblExpiry_Status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addComponent(lblCITY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblError_Make, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError_Make, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCar_Make, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModel_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel_year, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblNoOf_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_serial_No, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Serial_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerial_No, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModel_No, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Model_No, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpiry_Maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCity)
                                .addComponent(lblCITY, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtExpiry)
                                .addComponent(lblExpiry_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_save)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(351, 351, 351))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCar_MakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCar_MakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCar_MakeActionPerformed

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        String Car_Make = txtCar_Make.getText();
        int Model_Year = Integer.parseInt(txtYear.getText());
        int No_of_Seats = Integer.parseInt(txtSeats.getText());
        int Serial_No = Integer.parseInt(txt_serial_No.getText());
        int Model_No = Integer.parseInt(txt_Model_No.getText());
        String Availability = txtAvailability.getText();
        String City = txtCity.getText();
        String Expiry = txtExpiry.getText();
        
        Car ca = hist.addNewCar();
        ca.setCar_Make(Car_Make);
        SimpleDateFormat dte = new SimpleDateFormat("dd-MM-YYYY", Locale.getDefault());
        String Expiry_Date = dte.format(txt_Date.getDate());
        ca.setExpiery_Maintnance(Expiry_Date);
        ca.setModel_No(Model_No);
        ca.setModel_Year(Model_Year);
        ca.setNo_of_Seats(No_of_Seats);
        ca.setSerial_No(Serial_No);
        ca.setAvailability(Availability);
        ca.setCity(City);
        ca.setExpiry(Expiry);
        
            
            txtCar_Make.setText("");
            txtSeats.setText("");
            txtCity.setText("");
            txtAvailability.setText("");
            txtExpiry.setText("");
            txt_Model_No.setText("");
            txt_serial_No.setText("");
            txtYear.setText("");
            txt_Date.setDate(null);
            txtCity.setText("");
            JOptionPane.showMessageDialog(this, "New Car is added");
    
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void lblError_MakeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblError_MakeKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern PMake = Pattern.compile(PATTERN);
        Matcher MMake = PMake.matcher(txtCar_Make.getText());
        
        if(!MMake.matches()){
            lblError_Make.setText("Email Address Incorrect!");
        }
        else{
            lblError_Make.setText("mnm");
        }
    }//GEN-LAST:event_lblError_MakeKeyReleased

    private void lblModel_YearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblModel_YearKeyTyped
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern PYear = Pattern.compile(PATTERN);
        Matcher MYear = PYear.matcher(txtYear.getText());
        
        if(!MYear.matches()){
            lblModel_Year.setText("Email Address Incorrect!");
        }
        else{
            lblModel_Year.setText(null);
        }
    }//GEN-LAST:event_lblModel_YearKeyTyped

    private void txt_serial_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serial_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serial_NoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_save;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAv;
    private javax.swing.JLabel lblCITY;
    private javax.swing.JLabel lblCarMake;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblError_Make;
    private javax.swing.JLabel lblExpiry_Maintenance;
    private javax.swing.JLabel lblExpiry_Status;
    private javax.swing.JLabel lblModelN;
    private javax.swing.JLabel lblModel_No;
    private javax.swing.JLabel lblModel_Year;
    private javax.swing.JLabel lblModel_year;
    private javax.swing.JLabel lblNoOf_Seats;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerial_No;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbl_Serial_NO;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCar_Make;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpiry;
    private javax.swing.JTextPane txtSeats;
    private javax.swing.JTextPane txtYear;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_Model_No;
    private javax.swing.JTextField txt_serial_No;
    // End of variables declaration//GEN-END:variables
}
