/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Person;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author apurv
 */
public class CreateJPanel extends javax.swing.JPanel {

    Person person;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(Person person) {
        initComponents();
        this.person = person ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedicalrRecordNumber = new javax.swing.JLabel();
        lblHealthBenficiaryNumber = new javax.swing.JLabel();
        lblAccountNum = new javax.swing.JLabel();
        lblVehicalNum = new javax.swing.JLabel();
        lblLinkedInURL = new javax.swing.JLabel();
        lblIPAdd = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecordNum = new javax.swing.JTextField();
        txtHealthBenificiaryNum = new javax.swing.JTextField();
        txtAccountNumber = new javax.swing.JTextField();
        txtVehicalNumber = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        butSave = new javax.swing.JButton();
        lblDeviceIdentifier = new javax.swing.JLabel();
        txtDeviceIdentifier = new javax.swing.JTextField();
        lblLisenceNumber = new javax.swing.JLabel();
        txtLisenceNumber = new javax.swing.JTextField();
        lblEName = new javax.swing.JLabel();
        lblerrMail = new javax.swing.JLabel();
        lblErrorPhoneNum = new javax.swing.JLabel();
        lblErrorFaxNum = new javax.swing.JLabel();
        lblerrorSSN = new javax.swing.JLabel();
        lblerrormedicalRecordNum = new javax.swing.JLabel();
        lblerrorHealthBenNum = new javax.swing.JLabel();
        lblErrorAccountNum = new javax.swing.JLabel();
        lblErrorVehNum = new javax.swing.JLabel();
        lblerrorLinkedIn = new javax.swing.JLabel();
        lblerrorIPaddress = new javax.swing.JLabel();
        lblerrorDeviceManager = new javax.swing.JLabel();
        lblErrorLisenceNumber = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblPic = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE PROFILE");

        lblName.setText("NAME:");

        lblAddress.setText("Address:");

        lblDob.setText("DOB:");

        lblNumber.setText("PHONE NUMBER:");

        lblFaxNumber.setText("FAX NUMBER:");

        lblEmailAddress.setText("EMAIL ADDRESS:");

        lblSSN.setText("SSN:");

        lblMedicalrRecordNumber.setText("MED RECORD NUM:");

        lblHealthBenficiaryNumber.setText("HEALTH BENIFICIARY NUM:");

        lblAccountNum.setText("ACCOUNT NUM:");

        lblVehicalNum.setText("VEHICAL NUMBER:");

        lblLinkedInURL.setText("LINKEDIN:");

        lblIPAdd.setText("IP ADDRESS:");

        lblImage.setText("IMAGE:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyReleased(evt);
            }
        });

        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });
        txtFaxNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumKeyReleased(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyReleased(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        txtMedicalRecordNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumActionPerformed(evt);
            }
        });
        txtMedicalRecordNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumKeyReleased(evt);
            }
        });

        txtHealthBenificiaryNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthBenificiaryNumActionPerformed(evt);
            }
        });
        txtHealthBenificiaryNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealthBenificiaryNumKeyReleased(evt);
            }
        });

        txtAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNumberActionPerformed(evt);
            }
        });
        txtAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccountNumberKeyReleased(evt);
            }
        });

        txtVehicalNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicalNumberActionPerformed(evt);
            }
        });
        txtVehicalNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicalNumberKeyReleased(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyReleased(evt);
            }
        });

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });
        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyReleased(evt);
            }
        });

        butSave.setText("SAVE");
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        lblDeviceIdentifier.setText("DEVICE IDENTIFIER:");

        txtDeviceIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierActionPerformed(evt);
            }
        });
        txtDeviceIdentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDeviceIdentifierKeyReleased(evt);
            }
        });

        lblLisenceNumber.setText("LISENECE NUMBER");

        txtLisenceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLisenceNumberActionPerformed(evt);
            }
        });
        txtLisenceNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLisenceNumberKeyReleased(evt);
            }
        });

        lblEName.setForeground(new java.awt.Color(255, 0, 51));
        lblEName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblerrMail.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorPhoneNum.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorFaxNum.setForeground(new java.awt.Color(255, 0, 51));

        lblerrorSSN.setForeground(new java.awt.Color(255, 0, 51));

        lblerrormedicalRecordNum.setForeground(new java.awt.Color(255, 0, 0));

        lblerrorHealthBenNum.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorAccountNum.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorVehNum.setForeground(new java.awt.Color(255, 0, 51));

        lblerrorLinkedIn.setForeground(new java.awt.Color(255, 0, 51));

        lblerrorIPaddress.setForeground(new java.awt.Color(255, 0, 51));

        lblerrorDeviceManager.setForeground(new java.awt.Color(255, 0, 51));
        lblerrorDeviceManager.setText("  ");

        lblErrorLisenceNumber.setText("  ");

        btnImage.setText("Upload Image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(butSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLinkedInURL, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHealthBenficiaryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(lblMedicalrRecordNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVehicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHealthBenificiaryNum, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLisenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblerrormedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblerrorHealthBenNum, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(lblErrorAccountNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblerrorLinkedIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblErrorVehNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblerrorIPaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblErrorLisenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblerrorDeviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblErrorFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblerrorSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblErrorPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblerrMail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lblDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLisenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrMail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalrRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrormedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthBenficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthBenificiaryNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorHealthBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorVehNum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedInURL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorIPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorDeviceManager))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLisenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLisenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorLisenceNumber))
                .addGap(26, 26, 26)
                .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedicalRecordNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumActionPerformed

    private void txtHealthBenificiaryNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthBenificiaryNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthBenificiaryNumActionPerformed

    private void txtAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNumberActionPerformed

    private void txtVehicalNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicalNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicalNumberActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isEmpty()||
             txtAccountNumber.getText().isEmpty() ||
                txtAddress.getText().isEmpty() ||
                txtEmailAddress.getText().isEmpty() ||
                txtFaxNum.getText().isEmpty() ||
                txtHealthBenificiaryNum.getText().isEmpty() ||
                txtIPAddress.getText().isEmpty() ||
                txtLinkedIn.getText().isEmpty() ||
                txtMedicalRecordNum.getText().isEmpty() ||
                txtPhoneNumber.getText().isEmpty() ||
                txtSSN.getText().isEmpty() ||
                txtVehicalNumber.getText().isEmpty() ||
                txtDeviceIdentifier.getText().isEmpty() ||
                txtLisenceNumber.getText().isEmpty() || 
                !lblErrorPhoneNum.getText().equals("") ||
                !lblEName.getText().equals("") ||
                !lblErrorAccountNum.getText().equals("") ||
                !lblErrorFaxNum.getText().equals("") ||
                !lblErrorLisenceNumber.getText().equals("") ||
                !lblErrorVehNum.getText().equals("") ||
                !lblerrorDeviceManager.getText().equals("") ||
                !lblerrorHealthBenNum.getText().equals("") ||
                !lblerrorIPaddress.getText().equals("") ||
                !lblerrorSSN.getText().equals("") ||
                !lblerrormedicalRecordNum.getText().equals("") ||
                !lblerrMail.getText().equals("") ||
                !lblerrorLinkedIn.getText().equals("") ||
                lblPic.getText().equals("")
                ){
                 JOptionPane.showMessageDialog(this, " Fill in correct input");

        }else
        
            {
         person.setName(txtName.getText());
         person.setDOB(txtDob.getDate());
         person.setAccountNum(Long.parseLong(txtAccountNumber.getText()));
         person.setAddress(txtAddress.getText());
         person.setEmailAddress(txtEmailAddress.getText());
         person.setFaxNumber(Long.parseLong(txtFaxNum.getText()));
         person.setHealthPlanBenficiaryNum(Long.parseLong(txtHealthBenificiaryNum.getText()));
         person.setIPAdd(txtIPAddress.getText());
         person.setLinkedInURL(txtLinkedIn.getText());
         person.setMedicalrecordNum(Long.parseLong(txtMedicalRecordNum.getText()));
         person.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
         person.setSSN(txtSSN.getText());
         person.setVinum(Long.parseLong(txtVehicalNumber.getText()));
         person.setDeviceidentifier(Long.parseLong(txtDeviceIdentifier.getText()));
         person.setLisenceNum(Long.parseLong(txtLisenceNumber.getText()));
            JOptionPane.showMessageDialog(this, "Product Info Saved");
            }
       

    }//GEN-LAST:event_butSaveActionPerformed

    private void txtDeviceIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierActionPerformed

    private void txtLisenceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLisenceNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLisenceNumberActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{0,30}$";
        Pattern P = Pattern.compile(PATTERN);
        Matcher M = P.matcher(txtName.getText());
        if (!M.matches()){
            lblEName.setText("Naming convention not followed, use letters");
        }
        else {
            lblEName.setText("");
        }
        
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEmailAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9._]{0,32}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern E = Pattern.compile(PATTERN);
        Matcher L = E.matcher(txtEmailAddress.getText());
        if (!L.matches()){
        lblerrMail.setText("Please write the email address correctly");
        }
        else {
        lblerrMail.setText("");
        }        
    }//GEN-LAST:event_txtEmailAddressKeyReleased

    private void txtPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern PPhoneNum = Pattern.compile(PATTERN);
        Matcher LPhoneNum = PPhoneNum.matcher(txtPhoneNumber.getText());
        if (!LPhoneNum.matches()){
        lblErrorPhoneNum.setText("please write the Phone Number correctly");
        }
        else {
        lblErrorPhoneNum.setText("");
        }        
    }//GEN-LAST:event_txtPhoneNumberKeyReleased

    private void txtFaxNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern PFaxNum = Pattern.compile(PATTERN);
        Matcher LFaxNum = PFaxNum.matcher(txtFaxNum.getText());
        if (!LFaxNum.matches()){
        lblErrorFaxNum.setText("please write the Fax Number correctly");
        }
        else {
        lblErrorFaxNum.setText("");
        }        
    }//GEN-LAST:event_txtFaxNumKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$";
        Pattern PSSN = Pattern.compile(PATTERN);
        Matcher LSSN = PSSN.matcher(txtSSN.getText());
        if (!LSSN.matches()){
        lblerrorSSN.setText("SSN is not valid");
        }
        else {
        lblerrorSSN.setText("");
        }        
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtMedicalRecordNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[0-9]{0,7}$";
        Pattern PMRN = Pattern.compile(PATTERN);
        Matcher LMRN= PMRN.matcher(txtMedicalRecordNum.getText());
        if (!LMRN.matches()){
        lblerrormedicalRecordNum.setText("Medical record Number is not valid");
        }
        else {
        lblerrormedicalRecordNum.setText("");
        }        
    }//GEN-LAST:event_txtMedicalRecordNumKeyReleased

    private void txtHealthBenificiaryNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthBenificiaryNumKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[0-9]{0,7}$";
        Pattern PHBN = Pattern.compile(PATTERN);
        Matcher LHBN = PHBN.matcher(txtHealthBenificiaryNum.getText());
        if (!LHBN.matches()){
        lblerrorHealthBenNum.setText("Health Benificiary Number is not valid");
        }
        else {
        lblerrorHealthBenNum.setText("");}
    }//GEN-LAST:event_txtHealthBenificiaryNumKeyReleased

    private void txtAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNumberKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z0-9]{0,12}$";
        Pattern PAN = Pattern.compile(PATTERN);
        Matcher LAN = PAN.matcher(txtAccountNumber.getText());
        if (!LAN.matches()){
        lblErrorAccountNum.setText("Account  Number is not valid");
        }
        else {
        lblerrorHealthBenNum.setText("");}
           
    }//GEN-LAST:event_txtAccountNumberKeyReleased

    private void txtVehicalNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicalNumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,17}$";
        Pattern PVH = Pattern.compile(PATTERN);
        Matcher LVH = PVH.matcher(txtVehicalNumber.getText());
        if (!LVH.matches()){
        lblErrorVehNum.setText("Vehical Number is not valid");
        }
        else {
        lblErrorVehNum.setText("");}
        
    }//GEN-LAST:event_txtVehicalNumberKeyReleased

    private void txtLinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(\\b(https?|ftp|file)://)?[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]$";
        Pattern PLIK = Pattern.compile(PATTERN);
        Matcher LLIK = PLIK.matcher(txtLinkedIn.getText());
        if (!LLIK.matches()){
        lblerrorLinkedIn.setText("LinkedIn URL is not valid");
        }
        else {
        lblerrorLinkedIn.setText("");}
    }//GEN-LAST:event_txtLinkedInKeyReleased

    private void txtIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9.]{0,12}$";
        Pattern PIPAdd = Pattern.compile(PATTERN);
        Matcher LIpadd = PIPAdd.matcher(txtIPAddress.getText());
        if (!LIpadd.matches()){
        lblerrorIPaddress.setText("Ip Address is not valid");
        }
        else {
        lblerrorIPaddress.setText("");}
    }//GEN-LAST:event_txtIPAddressKeyReleased

    private void txtDeviceIdentifierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,6}$";
        Pattern PDI = Pattern.compile(PATTERN);
        Matcher LDI = PDI.matcher(txtDeviceIdentifier.getText());
        if (!LDI.matches()){
        lblerrorDeviceManager.setText("Device Identifier is not valid");
        }
        else {
        lblerrorDeviceManager.setText("");}
        
    }//GEN-LAST:event_txtDeviceIdentifierKeyReleased

    private void txtLisenceNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLisenceNumberKeyReleased
        // TODO add your handling code here:lblErrorLisenceNumber
        String PATTERN = "^[a-zA-Z0-9]{0,17}$";
        Pattern PLN = Pattern.compile(PATTERN);
        Matcher LLN = PLN.matcher(txtLisenceNumber.getText());
        if (!LLN.matches()){
        lblErrorLisenceNumber.setText("Lisence Number is not valid");
        }
        else {
        lblErrorLisenceNumber.setText("");}
    }//GEN-LAST:event_txtLisenceNumberKeyReleased

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        int image;
            JFileChooser uploadFile = new JFileChooser();
            image= uploadFile.showSaveDialog(null);
            if (image == JFileChooser.APPROVE_OPTION) {
                    File sImage = uploadFile.getSelectedFile();
                    person.setImage(sImage);
                    String[] pic = sImage.toString().split("\\\\");
                System.out.println(pic);
                lblPic.setText(pic[pic.length - 1]);
            }
    }//GEN-LAST:event_btnImageActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton butSave;
    private javax.swing.JLabel lblAccountNum;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEName;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblErrorAccountNum;
    private javax.swing.JLabel lblErrorFaxNum;
    private javax.swing.JLabel lblErrorLisenceNumber;
    private javax.swing.JLabel lblErrorPhoneNum;
    private javax.swing.JLabel lblErrorVehNum;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblHealthBenficiaryNumber;
    private javax.swing.JLabel lblIPAdd;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLinkedInURL;
    private javax.swing.JLabel lblLisenceNumber;
    private javax.swing.JLabel lblMedicalrRecordNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicalNum;
    private javax.swing.JLabel lblerrMail;
    private javax.swing.JLabel lblerrorDeviceManager;
    private javax.swing.JLabel lblerrorHealthBenNum;
    private javax.swing.JLabel lblerrorIPaddress;
    private javax.swing.JLabel lblerrorLinkedIn;
    private javax.swing.JLabel lblerrorSSN;
    private javax.swing.JLabel lblerrormedicalRecordNum;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDeviceIdentifier;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtHealthBenificiaryNum;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtLisenceNumber;
    private javax.swing.JTextField txtMedicalRecordNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtVehicalNumber;
    // End of variables declaration//GEN-END:variables
}
